<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * NomenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NomenRepository extends EntityRepository
{

    public function reverseNomen( $nomenId, $userId) {

        $em = $this->getEntityManager();
        
        $nomen = $this ->findOneBy( array( "nomen_id" => $nomenId, "actual_id" => NULL) );
        
        if ($nomen !== NULL) {
        
            $nomen->setActualId( $nomen->getNomenId() );
            $nomen->setDateCurr( new DateTime() );
            $nomen->setUserId( $userId );
        
            $nomen = $em->persist($nomen);
            $em->flush();
            
            $nomen = $this ->findOneBy( array( "nomen_id" => $nomenId ) );
        }

        return $nomen;
    }

}
