app:
    resource: "@AppBundle/Controller/"
    type:     annotation

login:
    pattern:   /login
    defaults:  { _controller: AppBundle:Security:login }

login_check:
    pattern:   /login_check

sign_up:
    pattern:   /sign-up
    defaults:  { _controller: AppBundle:Security:sign_up }

forgot_password:
    pattern:   /forgot-password
    defaults:  { _controller: AppBundle:Security:forgotPassword }

change_password:
    pattern:   /change-password
    defaults:  { _controller: AppBundle:Security:changePassword }

check_email:
    pattern:   /sign-up/check-email
    defaults:  { _controller: AppBundle:Security:checkEmail }

polis_new:
    pattern:   /polis-new
    defaults:  { _controller: AppBundle:Polis:polisNew }

polis_edit:
    pattern:   /polis-edit/{polisid}
    defaults:  { _controller: AppBundle:Polis:polisEdit }

polis_xls:
    pattern:   /polis-xls/{polisid}
    defaults:  { _controller: AppBundle:ExportXls:polisXls }

user_profile:
    pattern:   /user-profile
    defaults:  { _controller: AppBundle:Polis:userProfile }

order_list:
    pattern:   /order-list
    defaults:  { _controller: AppBundle:Polis:orderList }

desktop:
    pattern:   /desktop
    defaults:  { _controller: AppBundle:Main:desktop }

report:
    pattern:   /report
    defaults:  { _controller: AppBundle:Polis:report }

polis_list:
    pattern:   /polis-list
    defaults:  { _controller: AppBundle:Polis:polisList }

company_list:
    pattern:   /company-list
    defaults:  { _controller: AppBundle:Polis:companyList }

user_list:
    pattern:   /user-list
    defaults:  { _controller: AppBundle:Polis:userList }
