app:
    resource: "@AppBundle/Controller/"
    type:     annotation

login:
    pattern:   /login
    defaults:  { _controller: AppBundle:Security:login }

login_check:
    pattern:   /login_check

sign_up:
    pattern:   /sign-up
    defaults:  { _controller: AppBundle:Security:sign_up }

forgot_password:
    pattern:   /forgot-password
    defaults:  { _controller: AppBundle:Security:forgotPassword }

change_password:
    pattern:   /change-password
    defaults:  { _controller: AppBundle:Security:changePassword }

check_email:
    pattern:   /sign-up/check-email
    defaults:  { _controller: AppBundle:Security:checkEmail }

user_profile:
    pattern:   /user-profile
    defaults:  { _controller: AppBundle:Polis:userProfile }

order_list:
    pattern:   /order-list
    defaults:  { _controller: AppBundle:Polis:orderList }

order_view:
    pattern:   /order-view/{porderid}
    defaults:  { _controller: AppBundle:Polis:orderView }

order_edit:
    pattern:   /order-edit/{porderid}
    defaults:  { _controller: AppBundle:Polis:orderEdit }

desktop:
    pattern:   /desktop
    defaults:  { _controller: AppBundle:Main:desktop }

report:
    pattern:   /report
    defaults:  { _controller: AppBundle:Polis:report }

invoice_list:
    pattern:   /invoice-list
    defaults:  { _controller: AppBundle:Polis:invoiceList }

invoice_view:
    pattern:   /invoice-view/{pinvoiceid}
    defaults:  { _controller: AppBundle:Polis:invoiceView }

invoice_edit:
    pattern:   /invoice-edit/{pinvoiceid}
    defaults:  { _controller: AppBundle:Polis:invoiceEdit }

company_list:
    pattern:   /company-list
    defaults:  { _controller: AppBundle:Polis:companyList }

company_view:
    pattern:   /company-view/{pcompanyid}
    defaults:  { _controller: AppBundle:Polis:companyView }

company_edit:
    pattern:   /company-edit/{pcompanyid}
    defaults:  { _controller: AppBundle:Polis:companyEdit }

user_list:
    pattern:   /user-list
    defaults:  { _controller: AppBundle:Polis:userList }

user_view:
    pattern:   /user-view/{puserid}
    defaults:  { _controller: AppBundle:Polis:userView }

user_edit:
    pattern:   /user-edit/{puserid}
    defaults:  { _controller: AppBundle:Polis:userEdit }

invitation_sign_up:
    pattern:   /invitation-sign-up
    defaults:  { _controller: AppBundle:Polis:invitationSignUp }

send_invitation_sign_up:
    pattern:   /send-invitation-sign-up
    defaults:  { _controller: AppBundle:Polis:sendInvitationSignUp }

popup_prod_list:
    pattern:   /popup-prod-list
    defaults:  { _controller: AppBundle:Nomen:popupProdList }

popup_nomen_list:
    pattern:   /popup-nomen-list
    defaults:  { _controller: AppBundle:Nomen:popupNomenList }

nomen_list:
    pattern:   /nomen-list
    defaults:  { _controller: AppBundle:Nomen:nomenList }

nomen_view:
    pattern:   /nomen-view/{pnomenid}
    defaults:  { _controller: AppBundle:Nomen:nomenView }

nomen_edit:
    pattern:   /nomen-edit/{pnomenid}
    defaults:  { _controller: AppBundle:Nomen:nomenEdit }
