# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
    parameter_name: value

services:
    twig.extension.text:
      class: Twig_Extensions_Extension_Text
      tags:
      - { name: twig.extension }
    em:
        alias: doctrine.orm.entity_manager

    influencer.logger:
        class:     Symfony\Bridge\Monolog\Logger
        arguments: [app]
        calls:
            - [pushHandler, [@influencer.logger_handler]]

    influencer.logger_handler:
        class:     Monolog\Handler\StreamHandler       
        arguments: [%kernel.logs_dir%/%kernel.environment%.influencer.log, 200]

    influencer_logger:
        class:     AppBundle\Services\InfluencerLoggerService
        arguments: ["@influencer.logger", "@service_container"]

    mail_manager:
        class:     AppBundle\Lib\MailManager
        arguments: ["@mailer", "@twig", "@service_container"]
  
    security_service:
        class: AppBundle\Services\SecurityService
        arguments: ["@influencer_logger", "@em"]

    polis_service:
        class: AppBundle\Services\PolisService
        arguments: ["@influencer_logger", "@em", "@service_container"]

    i_key_service:
        class: AppBundle\Services\IKeyService
        arguments: ["@influencer_logger", "@em"]

    nomen_service:
        class: AppBundle\Services\NomenService
        arguments: ["@influencer_logger", "@em", "@service_container"]
